name: kinrec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pillow
  - ffmpeg
  - x264
  - scikit-image
  - pip:
      - git+https://github.com/vguzov/videoio.git@codecs
      - git+https://github.com/vguzov/KinZ-Python.git@kinect_addons
      - psutil
      - websockets